# Generated by Django 5.0.1 on 2024-01-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ballers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogador",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Está ativo?"),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="data_nasc",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
    ]
