# Generated by Django 5.0.1 on 2024-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ballers", "0003_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="abreviacao",
            field=models.CharField(max_length=3, verbose_name="Abreviação"),
        ),
        migrations.AlterField(
            model_name="time",
            name="apelido",
            field=models.CharField(max_length=30, verbose_name="Apelido"),
        ),
    ]
