# Generated by Django 5.0.1 on 2024-02-20 14:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ballers", "0004_alter_time_abreviacao_alter_time_apelido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campeonato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "descricao",
                    models.CharField(max_length=1000, verbose_name="Descrição"),
                ),
                ("times", models.ManyToManyField(to="ballers.time")),
            ],
            options={
                "verbose_name": "Campeonato",
                "verbose_name_plural": "Campeonatos",
            },
        ),
    ]
