# Generated by Django 5.0.1 on 2024-02-28 19:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ballers", "0005_campeonato"),
    ]

    operations = [
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("hora", models.TimeField()),
            ],
            options={
                "verbose_name": "Horario",
                "verbose_name_plural": "Horarios",
            },
        ),
        migrations.CreateModel(
            name="Quadra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, verbose_name="Nome da Quadra"),
                ),
            ],
            options={
                "verbose_name": "Quadra",
                "verbose_name_plural": "Quadras",
            },
        ),
    ]
