# Generated by Django 5.0.1 on 2024-02-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ballers", "0006_horario_quadra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horario",
            name="hora",
            field=models.TimeField(unique=True),
        ),
        migrations.AlterField(
            model_name="quadra",
            name="nome",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Nome da Quadra"
            ),
        ),
    ]
