# Generated by Django 5.0.1 on 2024-03-12 19:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ballers", "0007_alter_horario_hora_alter_quadra_nome"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Está ativo?"),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("finalizada", models.BooleanField(default=False)),
                ("gols_casa", models.IntegerField(blank=True, null=True)),
                ("gols_fora", models.IntegerField(blank=True, null=True)),
                (
                    "campeonato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ballers.campeonato",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ballers.horario",
                    ),
                ),
                (
                    "quadra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ballers.quadra"
                    ),
                ),
                (
                    "time_casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partidas_casa",
                        to="ballers.time",
                    ),
                ),
                (
                    "time_fora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partidas_fora",
                        to="ballers.time",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partida",
                "verbose_name_plural": "Partidas",
            },
        ),
        migrations.AddConstraint(
            model_name="partida",
            constraint=models.UniqueConstraint(
                fields=("data", "horario", "quadra"), name="exclusividade_quadra"
            ),
        ),
    ]
