# Generated by Django 5.0.1 on 2024-03-12 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ballers", "0008_partida_partida_exclusividade_quadra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partida",
            name="ativo",
        ),
    ]
